# How much XP should be removed every tick (1 second = 20 ticks)
# Must be between 0.0 and 1.0
xp-cost: 0.008

# Require permission xpflyx.fly to use /xpfly
enable-permission: false

# Prevent players from taking fall damage when they fall after flight turns off.
disable-fall-damage: true

messages:
  ran-out-of-xp: '&bYou can no longer fly because you are out of xp'
  not-a-player: '&cYou must be a player in order to execute this command.'
  command-flight-disabled: '&bXP flight has been disabled'
  command-flight-enabled: '&bXP flight has been enabled.'
  command-not-enough-xp: '&cYou do not have enough XP to start flying.'
  command-no-permission: '&cYou do not have permission to use this command.'
