name: XPFlyX
main: nl.rkslot.xpflyx.Main
version: '@project.version@'
author: Derkades
description: Allows players to fly at the cost of XP points

commands:
  xpfly:
    description: Toggles XP flight
    usage: /<command>
    aliases: [xpflyx]